### ISSUE TITLE
Failed to import the MGIS module.

### ISSUE THREAD

**Issue by RokyC** [thelfer/MFrontGenericInterfaceSupport#101]
I refer to "https://comet-fenics.readthedocs.io/en/latest/demo/plasticity_mfront/plasticity_mfront.py.html" installation TEFL and MGIS, 
     I run the following command on the terminal and execute it.However, the mGIS module cannot be found when running the Python file.
    The following is terminal execution:
     ->source. / mgis/master/install/env. sh
     -> mfront --obuild --interface=generic IsotropicLinearHardeningPlasticity.mfront
    Treating target : all
    The following library has been built :
     - libBehaviour.so :   IsotropicLinearHardeningPlasticity_AxisymmetricalGeneralisedPlaneStrain  
     IsotropicLinearHardeningPlasticity_Axisymmetrical IsotropicLinearHardeningPlasticity_PlaneStrain  
     IsotropicLinearHardeningPlasticity_GeneralisedPlaneStrain IsotropicLinearHardeningPlasticity_Tridimensional

**Comment by thelfer** [comment]
Hi @RokyC,

I don't see the error in your logs.

Would you try:

```bash
$ source ./mgis/master/install/env. sh
$ echo $PYTHONPATH
$ ls  ./mgis/master/install/lib/
$ python3
>>> import mgis
```

and give us the output of every single command.

Best,

Thomas

**Comment by RokyC** [comment]
> 
Thank you for your answer. This is the result after running：
(base) roky@roky-virtual-machine:~/ceshi$ source /home/roky/codes/mgis/master/install/env.sh
(base) roky@roky-virtual-machine:~/ceshi$ echo $PYTHONPATH
/home/roky/codes/mgis/master/install-273d02f3c8fd84ab6c9921abdade916e08997e9e/lib/python3.9/site-packages/:/home/roky/codes/tfel/master/install-22ec71681cf37302a57f9f4294019c5c5152b62d/lib/python3.9/site-packages/:
(base) roky@roky-virtual-machine:~/ceshi$ ls /home/roky/codes/mgis/master/install/env.sh
/home/roky/codes/mgis/master/install/env.sh
(base) roky@roky-virtual-machine:~/ceshi$ python3
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mgis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mgis'
>>>

**Comment by thelfer** [comment]
would you just list the files of the first directory pointed by PYTHONPATH (i.e. mgis/install-..../lib/python.../site-packages/)

**Comment by RokyC** [comment]
> 



> 

I seem to have found a problem, python3.9 does not exist in the lib file, I have reconfigured PYTHONPATH in env.sh. Thank you very much for your patient reply.
       
![image](https://user-images.githubusercontent.com/59686187/176126913-d9e799e3-4120-4603-ab12-b00c85017194.png)
