### ISSUE TITLE
[python bindings] Python bindings does not provide support for AuxiliaryStateVariables

### ISSUE THREAD

**Issue by pbouda95** [thelfer/MFrontGenericInterfaceSupport#102]
Hello,

It seems that python bindings does not provide a way to handle `@AuxilliaryStateVariables.`
I would be williful to self-assign this issue and work on it  but I am not sure where I need to start.

Cheers,

**Comment by pbouda95** [comment]
BTW, I am not sure if `mgis` itself provides something at his roots for that ...

**Comment by thelfer** [comment]
@pbouda95 There is no reason for mgis to handle auxiliary state variables. The distinction between "standard" state variables and auxiliary state variables is only meaningful inside `MFront`, there no reason for the calling solvers (and `mgis`) to make such a difference (i.e. everything is a state variable from their point of view !)

**Comment by pbouda95** [comment]
Hello @thelfer, 
I agree with you for the solver case. However, I thought it might be different if you think about `mgis` more as a higher level tool than `mtest` to perform integrations ... Thus you could have kept the same glossary as `mfront` and provide functions to handle them separately thereafter in a `MaterialStateManager` class for instance. But you've got a point :smile:

**Comment by thelfer** [comment]
`mtest` does not make any difference either ! :)
