### ISSUE TITLE
Is option enable-static still supported ?

### ISSUE THREAD

**Issue by Briffou** [thelfer/MFrontGenericInterfaceSupport#116]
I'm trying to compile MGIS with the `enable-static` option (available according to https://thelfer.github.io/mgis/web/install.html).

Specifically, I run

```
cmake ../MFrontGenericInterfaceSupport -Denable-c-bindings=ON -Denable-static=ON
```

But get the following error :
```
- Configuring done (5.0s)
CMake Error: INSTALL(EXPORT) given unknown export "MFrontGenericInterface-static"
CMake Error: INSTALL(EXPORT) given unknown export "MFrontGenericInterface-c-static"
-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

cmake version 3.26.4 (linux)

any clues ?

**Comment by thelfer** [comment]
Hi @Briffou
To be honest, I doubt that we ever tried this option.
I made some changes to make it work again but for a strange reason, `cmake` generates a shared library instead of a static one. I'll have a look this evening. If you have any idea of this, let me know.

**Comment by thelfer** [comment]
Fixed !
