### ISSUE TITLE
Support for intel llvm-based compilers ?

### ISSUE THREAD

**Issue by pbouda95** [thelfer/MFrontGenericInterfaceSupport#124]
MGIS seems to not handle icx/icpx llvm-based intel compilers, contrary to tfel.
This might be critical as icc ans icpc will be depreciated as of the end of 2023.

**Comment by thelfer** [comment]
I just tried icx/icpx  and it worked fine.

**Comment by pbouda95** [comment]
Hello @thelfer,

I don't think so. Here is a screeenshot of one of our compilation error while trying to use `icx` and `icpx` from oneAPI 2024:
![image](https://github.com/thelfer/MFrontGenericInterfaceSupport/assets/55626239/63f868b8-5c7d-44ca-940e-9da6f7ccfd25)

The same error occurs with oneAPI 2023.3 ...

Cheers,

**Comment by thelfer** [comment]
Ok, I'll check this.

________________________________
De : Pascal Bouda ***@***.***>
Envoyé : lundi 4 décembre 2023 13:19:43
À : thelfer/MFrontGenericInterfaceSupport
Cc : HELFER Thomas; Mention
Objet : Re: [thelfer/MFrontGenericInterfaceSupport] Support for intel llvm-based compilers ? (Issue #124)


Hello @thelfer<https://github.com/thelfer>,

I don't think so. Here is a screeenshot of one of our compilation error while trying to use icx and icpx from oneAPI 2024:
image.png (view on web)<https://github.com/thelfer/MFrontGenericInterfaceSupport/assets/55626239/63f868b8-5c7d-44ca-940e-9da6f7ccfd25>

The same error occurs with oneAPI 2023.3 ...

Cheers,

**Comment by thelfer** [comment]
Ok, I found the explanation: the intel compiler was not supported by my version of `cmake` and was detected as `Clang`

The only thing to do is the change line 144 of `cmake/modules/compilers.cmake` as follows:

~~~~
elseif(((CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
        (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM") OR
        (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")) AND
~~~~

**Comment by pbouda95** [comment]
Thanks @thelfer, it seems to work like a charm now :+1:
