### ISSUE TITLE
Unused const variable in static loadBehaviour 

### ISSUE THREAD

**Issue by dalphin5** [thelfer/MFrontGenericInterfaceSupport#126]
Dear all, 

I recently look up at the src/Behaviour.cxx file for info.

If i am not wrong, at line 60 of the static version of loadBehaviour, the variable "const auto fct=..." does not seem to be used.

Probably a relicate, it is not a bug but it may be better to delete this line (less code = less possible errors).

Regards.

Jérémy Dalphin

**Comment by thelfer** [comment]
You're right. It's fixed !
