### ISSUE TITLE
Implementation of an interface to the general purpose multibody dynamics solver MBDyn

### ISSUE THREAD

**Issue by octave-user** [thelfer/MFrontGenericInterfaceSupport#132]
Dear Mr. Thomas Helfer,

I would like to integrate your MFrontGenericInterfaceSupport library into the general purpose multibody dynamics solver [MBDyn](https://www.mbdyn.org/). So far, the small strain option is already working. However, the finite strain option seems to be more challenging. On one hand, I'm not 100% sure if I got the order of the tensor components right, and on the other hand I'm missing an option for the tangent operator. So, the derivative of the second Piola Kirchhoff Stress versus the deformation gradient "DS_DF" would be my favorite option.

You can find the current state of my implementation here:
[MFrontGenericInterfaceCSL](https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/mfront-csl-finite-strain/mbdyn/struct/solidcsl.cc?ref_type=heads#L59)
and here:
[ComputeStressElasticDefGrad](https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/mfront-csl-finite-strain/mbdyn/struct/solid.cc?ref_type=heads#L455)
I'm also providing a link to my reference implementation of Mooney Rivlin which I'm using to validate the [Signorini.mfront](https://thelfer.github.io/tfel/web/gallery/hyperelasticity/Signorini.mfront) model. So, far I was able to run a simple uni-axial tensile test with this model, but the result was not as expected. Probably, I was using Cauchy stress instead of First Piola Kirchhoff stress, although the stress_measure was set to PK1.
[MooneyRivlinStressTensor](https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/mfront-csl-finite-strain/mbdyn/struct/solidcsl.cc?ref_type=heads#L1026)

See also this link [mbdyn-input-develop.pdf](https://drive.google.com/file/d/1Un-Znh2bE702T9TsyrCb7XK5ItRKE4Ff/view?usp=sharing) at page 313.

Any help would be appreciated.

Best regards,
Reinhard

**Comment by thelfer** [comment]
@octave-user This is seems a very interesting project !
The order of the strain tensor and deformation gradient is given here: https://thelfer.github.io/tfel/web/tensors.html

**Comment by octave-user** [comment]
OK, the order of the tensor components and also the "load" function which I was using should be correct. Thank you!

But now I just saw, that the material parameters C01 and C10 were not consistent with my Mooney Rivlin parameters C1 and C2. So, the result seems to be correct now, but I need to check it in more detail.

**Comment by thelfer** [comment]
Great ! Let'us keep in touch and don't hesitate to make feedbacks or suggest proposals of improvement.

**Comment by octave-user** [comment]
Well, it would be nice to have an additional tangent operator, as I mentioned before. I think that such an option already exist, but it seems that it is not exposed by the generic interface. So, I would like to write something like this:
`
o.stress_measure = FiniteStrainBehaviourOptions::PK2;
o.tangent_operator = FiniteStrainBehaviourOptions::DPK2_DF;
`
Actually it is not really necessary, but I could simplify my code and reduce some overhead.

**Comment by octave-user** [comment]
It seems that the First Piola Kirchhoff Stress Tensor `PK1` is returned in a transposed format. 
Instead of
`T=(t11, t22, t33, t12, t21, t13, t31, t23, t32)`
I got
`T=(t11, t22, t33, t21, t12, t31, t13, t32, t23)`
Since this is not a symmetric tensor, the shear stress will be incorrect.

**Comment by thelfer** [comment]
Hi @octave-user, we use PK1 in FEniCS, XPER, Manta and many other projects. So far, nobody reported any issue. Could it be a confusion with the nominal stress ?

**Comment by octave-user** [comment]
Well, the difference may not be that obvious. I'm using a test case which was proposed by Konstantin Sedlan in 2000. I is about torsion tension coupling of an incompressible cylinder and a two parameter Mooney Rivlin material. That material is equivalent to MFront's Signorini model, provided that the parameter C20 is set to zero. I'm attaching a Maxima script which can be used, to generate the analytical expressions for the axial force and the torque.
[mooneyrivlin.tar.gz](https://github.com/thelfer/MFrontGenericInterfaceSupport/files/14982844/mooneyrivlin.tar.gz)
If you run that script, you get the following expressions for the torque `M` and the axial force `N`:
```

M=%pi*(C10+C01)*D*Ra^4

N=-(%pi*(C10+2*C01)*D^2*Ra^4)/3

```

If I'm using the Cauchy stress tensor, the output from MFront's Signorini model matches the analytical expression. However, if I'm using the First Piola Kirchhoff Stress Tensor and convert it back to Cauch stress, then the axial force is still correct, but the torque is no longer proportional to the twist `D`. But if I transpose the unsymmetric tensor, I get the correct result.

See the following test code:
[solidcsltest.cc](https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/mfront-csl-finite-strain/mbdyn/struct/solidcsltest.cc?ref_type=heads)

**Comment by octave-user** [comment]
See also page 102 of the following document:
[DissertationKonstantinSedlan.pdf](https://kobra.uni-kassel.de/themes/Mirage2/scripts/mozilla-pdf.js/web/viewer.html?file=/bitstream/handle/123456789/2007110219579/DissertationKonstantinSedlan.pdf?sequence=3&isAllowed=y#pagemode=thumbs)

**Comment by thelfer** [comment]
If the Cauchy stress tensor is correct, then the only source of error would be `convertCauchyStressToFirstPiolaKirchhoffStress` from the `TFEL/Math` library which was generated with a CCAS system (`maxima`).

The code is a bit clumsy, but I checked a few terms and they seem correct.

It can also checked that those terms would be different if this function returned the transpose of the First Piola-Kirchhoff stress.

**Comment by thelfer** [comment]
What math library are you using ? Rare are math library whose first array index is 1...

**Comment by thelfer** [comment]
Are you sure for this line:
 
 ```c++
  return F * PK1 / F.dDet();
  ```
  
  I have:

P  = s * F ^{-T} * J => s = (P * F^{T})/ J

s being symmetric, we can transpose the last relation:

s = F  * P^{T} / J

With this (hopefully correct) relation, you don't have to tranpose the MFront result.

**Comment by octave-user** [comment]
OK, I used the formulas from this book:

Richard Schwertassek
Oskar Wallrapp
Dynamik
flexibler Mehrkörpersysteme
Methoden der Mechanik zum
rechnergestützten Entwurf und zur
Analyse mechatronischer Systeme
Friedr. Vieweg & Sohn
Braunschweig/Wiesbaden
![image](https://github.com/thelfer/MFrontGenericInterfaceSupport/assets/61900614/fbbc1bb4-8feb-4e5c-a5da-ff15d21f1dab)

**Comment by thelfer** [comment]
It seems that the definition of PK1 is mostly a matter of convention. Some authors used the definition that I gave earlier, but other used the transposed version. I don't know which notations are used by Schwertassek et al. but I guess that:

- Delta is det(F)
- tau is the Cauchy stress
- S is Kirchhoff stress

If so, their SIGMA is the transpose of "my" PK1.

**Comment by octave-user** [comment]
Probably you are right. Maybe it would be a good idea to add a comment in the source code or documentation (e.g. in the class `FiniteStrainBehaviourOptions`).

**Comment by thelfer** [comment]
To be honest, I would expect most calculations with MGIS in many solvers to fail if I made such a mistake :)
But you are right about the documention. I'll do that ASAP.
Thanks again for your feed-backs !

**Comment by thelfer** [comment]
I added a note on the convention used to define PK1. Let me know if you need more help

**Comment by octave-user** [comment]
OK, now it is clear. Thank you very much for your support.

My next step would be, to include a few MFront behaviors in my testsuite and to update the user manual including examples and references to your work. After that, I would like to ask you, to review the related section of the manual and to add also a reference to [MBDyn](https://public.gitlab.polimi.it/DAER/mbdyn) at [https://thelfer.github.io/mgis/web/index.html](https://thelfer.github.io/mgis/web/index.html).

**Comment by thelfer** [comment]
Hi @octave-user, not problem. Tell me when it's ready.
If you're satisfied with MFront and MGIS, don't hesitate to make a talk a the MFront user days !

**Comment by octave-user** [comment]
Please have a look at the following sections of the attached draft version of MBDyn's manual and let me know if you have any suggestions!

- 2.10.36 MFront code generator
- 8.16 Solid Elements

[mbdyn-input-develop.pdf](https://github.com/thelfer/MFrontGenericInterfaceSupport/files/15099496/mbdyn-input-develop.pdf)

**Comment by thelfer** [comment]
@octave-user You manual seems fine to me.
I am a bit surprised that you have to specify *a priori* if the behaviour is finite or small strain, or the number of parameters.

**Comment by octave-user** [comment]
Well, MBDyn's constitutive laws and solid elements are based on templates with a fixed number of components of the stress/strain tensor (e.g. 6D for Green Lagrange Strain/Second Piola Kirchhoff Stress and 9D for Deformation Gradient and First Piola Kirchhoff Stress). Therefore, elements compiled for a 6D strain tensor cannot be used with MFront's finite strain behaviours which require a 9D strain tensor. The other way round would be possible somehow, but it is not implemented yet.

**Comment by octave-user** [comment]
In the meantime, I was playing a bit with examples from the [MFrontGallery](https://github.com/thelfer/MFrontGallery). Especially the `SignoriniHyperviscoelasticity` model seems to be very useful for my purposes. It worked without any issues, provided that all the viscoelastic parameters (g[0], g[1], g[2]) are set to zero. However, if I'm going to increase those parameters to a significant level, the solver is not able to converge any more. In contradiction to that, the `GeneralizedMaxwell` works without any issue, even if I raise the `ViscoelasticShearModulus` to very high values.

Does it mean that the viscoelastic contribution of the tangent operator for `SignoriniHyperviscoelasticity` is not consistent?

You can find a listing of my input file below:
`constitutive law: 1, name, "solid1", 9, mfront finite strain, library path, "/opt/mfront-gallery/lib/libHyperviscoelasticityBehaviours-generic.so", name, "SignoriniHyperviscoelasticity", properties, 10, "C10", 3.2307692307692310e+10, "C01", 8.0769230769230776e+09, "BulkModulus", 1.7499999999999997e+11, "C20", 0.0000000000000000e+00, "tau[0]", 1.0000000000000000e+02, "tau[1]", 1.0000000000000000e+03, "tau[2]", 1.0000000000000000e+04, "g[0]", 0.0000000000000000e+00, "g[1]", 0.0000000000000000e+00, "g[2]", 0.0000000000000000e+00;`

**Comment by thelfer** [comment]
@octave-user Would you tell me what kind of loadings you are considering ?

**Comment by octave-user** [comment]
It is about torsion of a bar with rectangular cross section and one rbe3 element at each end.
See the attached files:
![image](https://github.com/thelfer/MFrontGenericInterfaceSupport/assets/61900614/eb96603a-d1df-429b-9f82-fd35b2f4b442)
[solid.zip](https://github.com/thelfer/MFrontGenericInterfaceSupport/files/15187187/solid.zip)

**Comment by thelfer** [comment]
sorry, I don't have much time to learn the syntax of MBDyn's input files, but it seems that you make a time step of 1 (second ?). It this consistent with the internal times of the viscoelastic law ?

**Comment by octave-user** [comment]
OK, I think that I completely misunderstood the meaning of `g`. I thought, that it is something like the `ViscoelasticShearModulus` in the `GeneralizedMaxwell` model. But now I saw that it's unit should be rather non-dimensional. Since my values were scaled in [Pa], this was causing numerical truncation errors due to almost infinite stiffness.
`
H[i] = e[i]*H[i]+g[i]*(1-e[i])/(dtr)*(Si-Si_1);
`
However, if it is non-dimensional, it is not logical why it was declared as a `stress`. And also `tau` should be declared as `time` instead of `stress`, or am I wrong?.
```
@MaterialProperty stress tau[Nv];
@MaterialProperty stress g[Nv];
```

**Comment by octave-user** [comment]
Based on a finite difference approximation of the Jacobian, I can confirm that the tangent operator of the `SignoriniHyperviscoelasticity` model should be correct.
I can also confirm, that the results from `SignoriniHyperviscoelasticity` are consistent with the `GeneralizedMaxwell` model for uni-axial tension and small strains.

So, the only remaining issue is about the misleading declaration of `g` and `tau`. See the following pull request:
https://github.com/thelfer/MFrontGallery/pull/48

**Comment by thelfer** [comment]
> Based on a finite difference approximation of the Jacobian, I can confirm that the tangent operator of the SignoriniHyperviscoelasticity model should be correct.

Great !

> So, the only remaining issue is about the misleading declaration of g and tau. 

I'll have a look at it. I will try to enable `@UseQt true;` to see if the compiler can detect correct unit usage.

**Comment by octave-user** [comment]
Dear Thomas Helfer,

I would like to inform you, that the new mfront interface was merged into the main branch of MBDyn. So, I think that you could add [https://www.mbdyn.org/](https://www.mbdyn.org/) to the list of projects using MGIS ([https://thelfer.github.io/mgis/web/index.html](https://thelfer.github.io/mgis/web/index.html)).

Reinhard

**Comment by thelfer** [comment]
Great. Do you have:

- a description of MBDyn.
-  any demo/picture/video showing results using both MBDyn and MFront ?

so I could made some kind of announcement on LinkedIn (or if you do one, tell me, so I'll republish it)

**Comment by octave-user** [comment]
Well, you can use this one:
[MFront-Signorini-Hyperviscoelasticity.mpeg](https://youtu.be/I8HENx5mszA)

**Comment by octave-user** [comment]
And here is a description from https://www.mbdyn.org/:

MBDyn is the first and one of the few full-featured [free](https://www.gnu.org/philosophy/free-sw.html)[*](https://www.mbdyn.org/#Free) general purpose Multibody Dynamics analysis software, released under GNU’s GPL 2.1 (get a cached copy [here](https://github.com/mmorandi/MBDyn-web/blob/main/userfiles/downloads/gpl2.txt)).

It has been developed at the [Dipartimento di Scienze e Tecnologie Aerospaziali](https://www.aero.polimi.it/) (formerly Dipartimento di Ingegneria Aerospaziale) of the University “Politecnico di Milano”, Italy.

MBDyn features the integrated multidisciplinary simulation of multibody, multiphysics systems, including nonlinear mechanics of rigid and flexible bodies (geometrically exact & composite-ready beam and shell finite elements, component mode synthesis elements, lumped elements) subjected to kinematic constraints, along with smart materials, electric networks, active control, hydraulic networks, and essential fixed-wing and rotorcraft aerodynamics.

**Comment by thelfer** [comment]
https://www.linkedin.com/feed/update/urn:li:share:7198382956053176321/

**Comment by thelfer** [comment]
Hi @octave-user,
Could we close this issue ?
