### ISSUE TITLE
Installation instruction and dependencies

### ISSUE THREAD

**Issue by srmnitc** [thelfer/MFrontGenericInterfaceSupport#17]
This is part of the review of JOSS paper https://github.com/openjournals/joss-reviews/issues/2003

From the JOSS paper and associated documentation [webpage](https://thelfer.github.io/mgis/web/index.html), it is difficult to find any documentation on how to install or compile MGIS. Furthermore, the dependencies are also not documented in an easily accessible way.

**Comment by thelfer** [comment]
@srmnitc Thanks for this feed-back. I updated the `INSTALL-cmake.md` file to give an overview of the installation process. A new page has been added to the website: https://thelfer.github.io/mgis/web/install.html
