### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by srmnitc** [thelfer/MFrontGenericInterfaceSupport#18]
This is part of the review of JOSS paper https://github.com/openjournals/joss-reviews/issues/2003

A folder named tests is present in the repo, however, no documentation is provided on how to run the tests

**Comment by thelfer** [comment]
Running the test is part of the build process. The tests can be run by calling `ctest` (as usual in a `cmake` project), or by calling :

~~~~
$ make check
~~~~

at the top of the build directory.

**Note** The tests are only built if `TFEL/MFront` has been detected by `cmake`.
