### ISSUE TITLE
Feature request: Support for MFront parameters

### ISSUE THREAD

**Issue by chleh** [thelfer/MFrontGenericInterfaceSupport#2]
First of all thanks for this library, based on the unit tests we could implement MFront support into our FEM code in seven days, including tests. Especially your unit tests were really helpful.

I recognized that `Behaviour::parameters` is always empty. There is some code to parse the parameters from MFront behaviour libraries
https://github.com/thelfer/MFrontGenericInterfaceSupport/blob/9b0884a042c288d4d6ac55db458ec851dc1b1b89/src/Behaviour.cxx#L286
However, it's commented and seems somewhat outdated. Are you planning to implement support for parameters in the near future?

**Comment by thelfer** [comment]
Hi @chleh,
Thanks for using `MGIS` !
This library is still young, so it does have a few shortcomings, like parameters' support. I'll implement this rapidely.
Beware that, do to the support of the stored and disspated energies, you must use the development branches of `TFEL` to use the development branches of `MGIS`.
Do no hesitate to make other feed-backs or feature requests.
Best,
Thomas

**Comment by thelfer** [comment]
Initial support for parameters has been merged in the `master` branch.

The `Behaviour` class now has the following members:
- `params`: list of real parameters
- `iparams`: list of integer parameters
- `usparams`: list of unsigned short parameters

The parameters' values can be changed through the `setParameters` functions in `C++`.

Appropriate bindings have been made for `python`.

What is missing:
- ability to get the default value of a parameter
- ability to get the current value of a parameter
- ability to get the bounds of a parameter
- `C` bindings.
- comprehensive tests
- backport all of this in the `rliv-1.0` branch

**Comment by chleh** [comment]
That was really fast, thanks. We'll test that. For me the issue is solved now.

**Comment by thelfer** [comment]
Just add tests on parameters.

**Comment by thelfer** [comment]
Bindings and tests are now ok. I'l merge `master` and `rliv-1.0` branches and close the issue.
