### ISSUE TITLE
Community guidelines absent

### ISSUE THREAD

**Issue by srmnitc** [thelfer/MFrontGenericInterfaceSupport#20]
This is part of the review of JOSS paper https://github.com/openjournals/joss-reviews/issues/2003

Community guidelines as present in the JOSS paper - `Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support` are absent.

**Comment by thelfer** [comment]
@srmnitc I adapted the `CONTRIBUTE.md` file for the `html5boilerplate` project which I found very clear. I added this new `CONTRIBUTE.md` in the root directory of the project and updated the website. Need to do the same for all my other projects.
