### ISSUE TITLE
Author affiliations are not complete

### ISSUE THREAD

**Issue by srmnitc** [thelfer/MFrontGenericInterfaceSupport#21]
This is part of the review of JOSS paper https://github.com/openjournals/joss-reviews/issues/2003

Author affiliations should have complete addresses

**Comment by thelfer** [comment]
@srmnitc Could you be more specific ? Is the issue only related to the JOSS paper ? If so, each authors seems to have properly filled its affiliations in the paper, don't they ?

**Comment by srmnitc** [comment]
@thelfer Yes this is only related to the paper.  No, they are incomplete. For example, number 3 Wärtsilä, Number 4, Number 6 etc. The complete address of affiliated institution should be present. All of the already published JOSS papers seems to follow this.

**Comment by thelfer** [comment]
@srmnitc Can I close the issue ?

**Comment by srmnitc** [comment]
1, 7 and 8 still not fixed

**Comment by thelfer** [comment]
Updated my own affiliation. Waiting for Thomas and Dmitri updates.

**Comment by thelfer** [comment]
@srmnitc Affliations shall be correct by now.
