### ISSUE TITLE
[CMake]: Exporting MGIS build tree for use by external projects

### ISSUE THREAD

**Issue by pbouda95** [thelfer/MFrontGenericInterfaceSupport#25]
Hello Thomas,

Everything is in the subject. For further details, see [request #4](https://github.com/thelfer/tfel/issues/4) for TFEL repository.

Cheers,
Pascal

**Comment by thelfer** [comment]
The following files are now generated and exported:

- `MFrontGenericInterfaceConfig.cmake`: configuration file for the `MFrontGenericInterface` library which contains the `C++` core library of `MGIS`.
- `MFrontGenericInterface-cConfig.cmake`: configuration file for the `MFrontGenericInterface` library which contains the `c` binding of `MGIS`.
- `MFrontGenericInterface-fortranConfig.cmake`: configuration file for the `MFrontGenericInterface-fortran` library which contains the `fortran` bindings of `MGIS`.

Those files can be used as follows:

~~~~{.cmake}
find_package (MFrontGenericInterface REQUIRED)
~~~~

The previous instruction imports the `mgis::MFrontGenericInterface` target, which can be used as follows:

~~~~{.cmake}
  target_link_libraries(HybridHighOrder
	PRIVATE mgis::MFrontGenericInterface)
~~~~
