### ISSUE TITLE
[Fortran] Get internal state variables array size via fortran bindings

### ISSUE THREAD

**Issue by pbouda95** [thelfer/MFrontGenericInterfaceSupport#27]
Hello Thomas,

In Behaviour class, subroutine BEHAVIOUR_GET_INTERNAL_STATE_VARIABLE_OFFSET enables InternalStateVariables array partitioning. However, the whole array size is unknown a priori. This may be useful when initializing FE code fortran arrays.

Is there a way to gain access to it ?

Cheers,
Pascal

**Comment by thelfer** [comment]
Hi Pascal,
as you know, `fortran` bindings still are in an early stage of development.
No  function returning the size of the internal state variables are not exposed so far. I'll try to do this quickly.
Thomas
