### ISSUE TITLE
Missing block jacobian info in python binding

### ISSUE THREAD

**Issue by bleyerj** [thelfer/MFrontGenericInterfaceSupport#28]
When inspecting the behaviour object in Python, there seems to be no information about the block structure of the jacobian

**Comment by thelfer** [comment]
The tangent operator blocks are now available in the `python` bindings
under the `tangent_operator_blocks` property of the `Behaviour` class.

Those blocks are accessible as an array of tuples of instances of the
`Variable` class.

This feature can be used as follows:

~~~~{.python}
import mgis.behaviour as mgis_bv

h = mgis_bv.Hypothesis.Tridimensional
b = mgis_bv.load('src/libBehaviour.so','StationaryHeatTransfer2',h)
for t in b.tangent_operator_blocks:
    print('d{}_d{}'.format(t[0].name,t[1].name))
~~~~
