### ISSUE TITLE
[bindings] Variables array size depending on type+modelling hypothesis 

### ISSUE THREAD

**Issue by pbouda95** [thelfer/MFrontGenericInterfaceSupport#30]
Thomas,

Within the Behaviour object, one can get parameters, state variables (external+internal) or material properties type (scalar, vector tensor or stensor) using current bindings. However, it is not possible to get their size depending on the modelling hypothesis.

I can try to do something about this, but I am not sure if this is really relevant ... 
Or maybe there is an another way to proceed ?

Thanks in advance for your advices,

Cheers,
Pascal

**Comment by thelfer** [comment]
Hi Pascal,
Material proeperties, parameters and external state variables are always scalars so their size does not depend on modelling hypothesis.
For state variables, you can indeed get access to its type, but I did not expose any method to get their size as a function of the modelling hypothesis.
I'll fix this ASAP.

**Comment by thelfer** [comment]
The `get_variable_size` function is now available in the
`mgis_behaviour` module. This function returns the size of a variable
(i.e. the number of components) for the given hypothesis.
