### ISSUE TITLE
Function for checking if the behaviour is a Finite Strain one

### ISSUE THREAD

**Issue by bleyerj** [thelfer/MFrontGenericInterfaceSupport#33]
It would be nice to have a function returning if a behaviour is a finite-strain one so that one can call the appropriate method (with finite-strain options in this case) when loading the behaviour

**Comment by thelfer** [comment]
Just to mention, in `C++`, you may have access to those information using the `LibraryManager` class. However, this class is very low level and is not available in any bindings.

**Comment by thelfer** [comment]
Just added the `isStandadFiniteStrainBehaviour` function. Would you test it ?

**Comment by bleyerj** [comment]
works fine!
