### ISSUE TITLE
Issues with paper

### ISSUE THREAD

**Issue by srmnitc** [thelfer/MFrontGenericInterfaceSupport#35]
This is part of the review of JOSS paper openjournals/joss-reviews#2003

- The JOSS paper has some typos which need to fixed.
- The first page of the paper has numerous short paragraphs, which in my opinion affects the readability.
- Another point is about citations. Statements in the paper such as `This is error-prone and may lead to spurious or even worse inexact results` and `While this causes memory fragmentation, this is the most frequent choice, would be reinforced with suitable citations`.

**Comment by thelfer** [comment]
Hi @srmnitc,

> Statements in the paper such as This is error-prone and may lead to spurious or even
> worse inexact results and While this causes memory fragmentation, this is the most frequent
> choice, would be reinforced with suitable citations.

This is indeed a difficult point coming most notably from our own experiences of building complex simulations. I don't know if I can find any citations on that matter.

Would it be ok if we introduce proper word of cautions, such as: "According to the authors experience...", "One drawback of this approach is that it may lead to memory fragmentation"

**Comment by srmnitc** [comment]
I think you could also specify some reason as to why it is error prone and so on.

**Comment by thelfer** [comment]
For the third point, here is a small paragraph which highlighs how traditional approaches are error-prone:

> In the authors' experience, this is error-prone in particular for
> inexperienced users and may lead to spurious or even worse inexact
> results. For example, when material properties such as the Young Modulus
> or the Poission ratio, are required by the behaviour, those are
> generally defined in the solver input file by an array of values and
> potentiel checks are limited to the size of the array. An user may thus
> invert two material properties. If those two material properties have
> the same order of magnitudes, computations might lead to a physically
> consistent result, altough a wrong result.

**Comment by thelfer** [comment]
@srmnitc 

> * The JOSS paper has some typos which need to fixed.

I tried to fix that with the help of the co-authors and a colleague who is a native english speaker. English is hopefuly acceptable now.

> * The first page of the paper has numerous short paragraphs, which in my opinion affects the readability.

Apart from the first line, the other paragraphs have more than 7 lines. Each develops a specific idea, which is a common convention in French. 

> * Another point is about citations. Statements in the paper such as `This is error-prone and may lead to spurious or even worse inexact results` and `While this causes memory fragmentation, this is the most frequent choice, would be reinforced with suitable citations`.

The statement "This is error-prone" has been discussed more in details.
The statement about memory fragmentation has been removed because detailled discussion of this point is out of the scope of the paper.

**Comment by srmnitc** [comment]
Thanks @thelfer , everything looks okay now. One last point - maybe Mohr-Coulumb yield criterion needs a citation?

**Comment by thelfer** [comment]
Done ! Thanks again for the review.
