### ISSUE TITLE
[fortran] Some bindings are returning a NaN value

### ISSUE THREAD

**Issue by pbouda95** [thelfer/MFrontGenericInterfaceSupport#39]
Several bindings are returning a NaN value, whichever the arguments:
1. material_state_manager_get_uniform_external_state_variables
2. material_state_manager_get_uniform_material_property

My first investigations were not fruitful so I am opening this ticket ...

Cheers,

**Comment by thelfer** [comment]
The issue boils down to this test, which was meant to invalidate the result if the calll was unsucessful:  

~~~~{.fortran}
  if( r % exit_status .eq. MGIS_SUCCESS) then
       v = ieee_value(v, ieee_quiet_nan)
    end if
~~~~

This shall be:

~~~~{.fortran}
  if( r % exit_status .ne. MGIS_SUCCESS) then
       v = ieee_value(v, ieee_quiet_nan)
    end if
~~~~

Thanks for reporting !
