### ISSUE TITLE
Inform the calling code about @DissipatedEnergy and/or @InternalEnergy

### ISSUE THREAD

**Issue by ojamond** [thelfer/MFrontGenericInterfaceSupport#54]
For application codes which manage the memory using BehaviourDataView, it would be nice to be able to know if the loaded behavior as @DissipatedEnergy and/or @InternalEnergy blocks, so that the calling code could know if it has to allocate memory for that or not.

**Comment by thelfer** [comment]
@ojamond Would test and eventually close this ticket ?

**Comment by thelfer** [comment]
The `Behaviour` class now exposes two new boolean data members:

- `computesStoredEnergy`: if true, the behaviour computes the stored energy
- `computesDissipatedEnergy`: if false, the behaviour computes the dissipated energy
