### ISSUE TITLE
Compilation errors with "@StrainMeasure GreenLagrange"

### ISSUE THREAD

**Issue by ojamond** [thelfer/MFrontGenericInterfaceSupport#6]
When using "@StrainMeasure GreenLagrange;", one get some errors like when building (clang):

```
error: use of undeclared identifier 'gradients0_old'; did you mean
'gradients0'
```
```
error: use of undeclared identifier 'thermodynamic_forces0_old'; did
you mean 'thermodynamic_forces0'?
```
`error: use of undeclared identifier 'K_old'`

No problem with "@StrainMeasure Henky;"

**Comment by thelfer** [comment]
Hi Olivier,
The trouble is related to `MFront` and not `MGIS`.
Thomas

**Comment by thelfer** [comment]
Fixed in:
- `TFEL`' revision 2252 in `trunk`
- `TFEL`' revision 2253 in  `rliv-3.2`
