### ISSUE TITLE
help accessing mgis.fenics installed through spack

### ISSUE THREAD

**Issue by minamdar** [thelfer/MFrontGenericInterfaceSupport#75]
Hello,
I am trying to install mgis via spack. Specifically, I want to use mgis.fenics libraries to run the demos created by J. Bleyer. To that end, I did the following. 

1) Downloaded spack. Created and activated a new environment 'fenics-env'
2) Installed fenics in the environment 'fenics-env' using: spack install fenics
3) Installed 'mgis' in the same env as 2) using: spack install mgis

Now, while staying in the same env 'fenics-env', when I start the python console and type:

4) import dolfin as df

the libraries load just fine. However, when I type

5) import mgis.fenics as mf

I get an error that mgis library is not found. 

When I search externally, I see that mgis libraries are installed in the opt/ folder of spack. Could you please help me? 
My understanding of such matters is at a bare minimum. I am using OSX-Catalina and apple clang-11.0. 

Thank you.
Mandar

**Comment by thelfer** [comment]
Hi Mandar,

You have to specificy that you want the `python` bindings for `mgis`. Under Linux, this works like a charm:

```bash
$ spack install fenics tfel +python mgis +python
$ spack load fenics tfel mgis
$ python3 
Python 3.8.12 (default, Oct 28 2021, 15:21:40) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mgis.fenics
```

On Mac Os, I did have some trouble due to the dependency to `numpy` which depends on `blas` and `openblas` did not compile on my box. Let me know if you have more success than I did.

Best,
Thomas
