### ISSUE TITLE
MFEM-MGIS Compilation issue: mgis::span has not been declared

### ISSUE THREAD

**Issue by rprat-pro** [thelfer/MFrontGenericInterfaceSupport#92]
Hi,

I'm trying to compile the current version of MFEM-MGIS (with gcc 9.3.0) using the current master of MGIS. I got the following error with mgis::span just below. There is a span.hxx file in include/MGIS so I wonder why in my case this class is not declared.

`[ 24%] Building CXX object src/CMakeFiles/MFEMMGIS.dir/BehaviourIntegratorBase.cxx.o`
`In file included from /home/rp269144/codes/mfem-mgis/src/BehaviourIntegratorBase.cxx:10:`
`/spack/opt/spack/linux-debian10-icelake/gcc-9.3.0/mgis-master-rybrxdfo6vbfvjapr7ldys3yxmcnbems/include/MGIS/Behaviour/Integrate.hxx:147:45: error: 'mgis::span' has not been declared`
`  147 |                                             mgis::span<const real>);`

Thanks in advance!

**Comment by thelfer** [comment]
Hi @rprat-pro,
Looks like there is an include missing in `MGIS/Behaviour/Integrate.hxx`.
I updated the `master` branch of `mgis`. Would you try to update it ?
Thomas

**Comment by rprat-pro** [comment]
Great, it works for me!

Thank you,
Raphaël
